"""
MCP Server - Silver Tier Component
Basic Model Context Protocol server exposing external actions
Provides structured request/response for email sending
"""

import json
from pathlib import Path
from datetime import datetime


class MCPServer:
    def __init__(self, vault_path):
        self.vault_path = Path(vault_path)
        self.email_skill_path = self.vault_path / "Silver_Layer" / "skills" / "email_skill.md"
        self.pending_approval_folder = self.vault_path / "Pending_Approval"

    def handle_request(self, request):
        """
        Handle incoming MCP request
        Returns structured response
        """
        try:
            action = request.get('action')
            params = request.get('params', {})

            if action == 'send_email':
                return self.send_email(params)
            else:
                return {
                    'status': 'error',
                    'message': f'Unknown action: {action}',
                    'timestamp': datetime.now().isoformat()
                }

        except Exception as e:
            return {
                'status': 'error',
                'message': str(e),
                'timestamp': datetime.now().isoformat()
            }

    def send_email(self, params):
        """
        Send email action (simulated)
        In production, this would integrate with email service
        """
        # Validate required parameters
        required = ['recipient', 'subject', 'body']
        missing = [p for p in required if p not in params]

        if missing:
            return {
                'status': 'error',
                'message': f'Missing required parameters: {", ".join(missing)}',
                'timestamp': datetime.now().isoformat()
            }

        # Extract parameters
        recipient = params['recipient']
        subject = params['subject']
        body = params['body']
        tone = params.get('tone', 'professional')
        attachments = params.get('attachments', [])

        # Apply email skill logic
        email_draft = self.compose_email(recipient, subject, body, tone)

        # Save to pending approval
        draft_path = self.save_email_draft(email_draft, recipient, subject)

        # Simulate sending (in production, would actually send)
        result = self.simulate_send(email_draft, recipient)

        # Log action
        self.log_email_action(recipient, subject, result['status'])

        return {
            'status': 'success',
            'action': 'send_email',
            'result': result,
            'draft_path': str(draft_path),
            'message': 'Email draft created and saved to Pending_Approval',
            'timestamp': datetime.now().isoformat()
        }

    def compose_email(self, recipient, subject, body, tone):
        """
        Compose email using email_skill guidelines
        """
        # Read email skill for guidance
        try:
            with open(self.email_skill_path, 'r', encoding='utf-8') as f:
                skill_content = f.read()
        except FileNotFoundError:
            skill_content = None

        # Format email
        email = f"""To: {recipient}
Subject: {subject}
Tone: {tone.title()}

---

{body}

---

Best regards,
AI Employee System

*This email was composed using the Email Skill*
*Generated: {datetime.now().isoformat()}*
"""
        return email

    def save_email_draft(self, email_draft, recipient, subject):
        """Save email draft to Pending_Approval for human review"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_subject = subject.replace(' ', '_')[:50]
        filename = f"email_draft_{safe_subject}_{timestamp}.md"
        filepath = self.pending_approval_folder / filename

        content = f"""# Email Draft - Pending Approval

**Recipient:** {recipient}
**Subject:** {subject}
**Created:** {datetime.now().isoformat()}
**Status:** Awaiting Approval

---

## Email Content

{email_draft}

---

## Approval Instructions

To approve and send this email:
1. Review the content above
2. Make any necessary edits
3. Create a file named: `{filename}.approved.flag`
4. The system will detect approval and send the email

To reject:
1. Create a file named: `{filename}.rejected.flag`
2. Add rejection reason in the file

---

*Generated by MCP Server (Silver Layer)*
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"📧 Email draft saved: {filename}")
        return filepath

    def simulate_send(self, email_draft, recipient):
        """
        Simulate sending email
        In production, this would use SMTP or email service API
        """
        print(f"\n{'='*60}")
        print("SIMULATED EMAIL SEND")
        print(f"{'='*60}")
        print(email_draft)
        print(f"{'='*60}\n")

        return {
            'sent': False,
            'simulated': True,
            'recipient': recipient,
            'message': 'Email saved to Pending_Approval. Awaiting human approval to send.',
            'timestamp': datetime.now().isoformat()
        }

    def log_email_action(self, recipient, subject, status):
        """Log email action"""
        log_dir = self.vault_path / "Silver_Layer" / "logs"
        log_dir.mkdir(exist_ok=True)
        log_file = log_dir / f"mcp_server_{datetime.now().strftime('%Y-%m-%d')}.log"

        with open(log_file, 'a', encoding='utf-8') as f:
            timestamp = datetime.now().strftime('%H:%M:%S')
            f.write(f"[{timestamp}] send_email: {recipient} - {subject} - {status}\n")

    def start(self, port=8080):
        """
        Start MCP server
        In production, this would be a proper HTTP/WebSocket server
        For now, provides a simple interface
        """
        print(f"🚀 MCP Server - Silver Layer")
        print(f"📁 Vault: {self.vault_path}")
        print(f"🔌 Port: {port} (simulated)")
        print(f"\nAvailable actions:")
        print(f"  - send_email")
        print(f"\nServer ready to accept requests\n")


def main():
    """
    Example usage of MCP Server
    """
    vault_path = Path(__file__).parent.parent.parent
    server = MCPServer(vault_path)

    # Start server
    server.start()

    # Example request
    print("Example Request:")
    example_request = {
        'action': 'send_email',
        'params': {
            'recipient': 'client@example.com',
            'subject': 'Project Update - Week 3',
            'body': '''Hi there,

Quick update on the project:

✅ Completed Phase 1
🔄 Starting Phase 2 this week
📅 On track for March 15 deadline

Let me know if you have any questions.''',
            'tone': 'professional'
        }
    }

    print(json.dumps(example_request, indent=2))
    print("\nProcessing request...\n")

    # Handle request
    response = server.handle_request(example_request)

    print("Response:")
    print(json.dumps(response, indent=2))


if __name__ == "__main__":
    main()
