"""
LinkedIn Poster - Silver Tier Component
Reads approved content and generates LinkedIn posts using the linkedin_generation_skill
"""

import json
from pathlib import Path
from datetime import datetime


class LinkedInPoster:
    def __init__(self, vault_path):
        self.vault_path = Path(vault_path)
        self.approved_folder = self.vault_path / "Approved"
        self.generated_posts_folder = self.vault_path / "Silver_Layer" / "generated_posts"
        self.pending_approval_folder = self.vault_path / "Pending_Approval"
        self.skill_path = self.vault_path / "Silver_Layer" / "skills" / "linkedin_generation_skill.md"

        # Ensure folders exist
        self.generated_posts_folder.mkdir(parents=True, exist_ok=True)

    def read_skill_definition(self):
        """Read the LinkedIn generation skill for guidance"""
        try:
            with open(self.skill_path, 'r', encoding='utf-8') as f:
                return f.read()
        except FileNotFoundError:
            print(f"⚠️  Skill definition not found: {self.skill_path}")
            return None

    def find_approved_content(self):
        """Find approved content files that can be turned into LinkedIn posts"""
        approved_files = list(self.approved_folder.glob("*.md"))
        return approved_files

    def generate_linkedin_post(self, source_file):
        """
        Generate LinkedIn post from approved content
        This calls the linkedin_generation_skill logic
        """
        # Read source content
        with open(source_file, 'r', encoding='utf-8') as f:
            content = f.read()

        # Extract key information
        title = source_file.stem

        # Apply LinkedIn generation skill logic
        # In production, this would call Claude Code with the skill
        post = self.apply_linkedin_skill(title, content)

        return post

    def apply_linkedin_skill(self, title, content):
        """
        Apply LinkedIn generation skill logic
        This simulates calling the skill - in production would use Claude Code API
        """
        # Simulated post generation following the skill guidelines
        post = f"""🚀 {title}

After working on this, here are the key insights:

→ {self.extract_key_point(content, 1)}
→ {self.extract_key_point(content, 2)}
→ {self.extract_key_point(content, 3)}

This approach has helped us achieve measurable results.

What's your experience with this?
Drop a comment below. 👇

#Business #Productivity #Innovation #Leadership

---
*Generated by Silver Layer LinkedIn Automation*
*Source: {title}*
*Generated: {datetime.now().isoformat()}*
"""
        return post

    def extract_key_point(self, content, index):
        """Extract key points from content (simplified)"""
        lines = [line.strip() for line in content.split('\n') if line.strip() and not line.startswith('#')]
        if index <= len(lines):
            return lines[index - 1][:100]
        return "Key insight from the content"

    def save_post_draft(self, post, source_file):
        """Save generated post as draft"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"linkedin_post_{source_file.stem}_{timestamp}.md"
        filepath = self.generated_posts_folder / filename

        draft_content = f"""# LinkedIn Post Draft

**Source:** {source_file.name}
**Generated:** {datetime.now().isoformat()}
**Status:** Pending Review

---

## Post Content

{post}

---

## Next Steps

1. Review the post content
2. Edit if needed
3. Move to /Pending_Approval for human approval
4. After approval, post to LinkedIn

## Metadata

- Character count: {len(post)}
- Hashtag count: {post.count('#')}
- Source file: {source_file}
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(draft_content)

        print(f"✅ Post draft saved: {filename}")
        return filepath

    def move_to_approval(self, draft_path):
        """Move draft to Pending_Approval for human review"""
        approval_path = self.pending_approval_folder / draft_path.name
        draft_path.rename(approval_path)
        print(f"📋 Moved to Pending_Approval: {draft_path.name}")
        return approval_path

    def process_content(self, source_file):
        """Process a single content file into LinkedIn post"""
        print(f"\n📄 Processing: {source_file.name}")

        # Generate post using skill
        post = self.generate_linkedin_post(source_file)

        # Save draft
        draft_path = self.save_post_draft(post, source_file)

        # Move to approval queue
        approval_path = self.move_to_approval(draft_path)

        # Log action
        self.log_action(source_file, approval_path)

        return approval_path

    def log_action(self, source_file, approval_path):
        """Log post generation"""
        log_dir = self.vault_path / "Silver_Layer" / "logs"
        log_dir.mkdir(exist_ok=True)
        log_file = log_dir / f"linkedin_poster_{datetime.now().strftime('%Y-%m-%d')}.log"

        with open(log_file, 'a', encoding='utf-8') as f:
            timestamp = datetime.now().strftime('%H:%M:%S')
            f.write(f"[{timestamp}] Generated post from: {source_file.name} → {approval_path.name}\n")

    def run(self, source_file=None):
        """
        Main execution
        If source_file provided, process that file
        Otherwise, process all approved content
        """
        print("🤖 LinkedIn Poster - Silver Layer")
        print(f"📁 Vault: {self.vault_path}\n")

        if source_file:
            # Process specific file
            source_path = Path(source_file)
            if source_path.exists():
                self.process_content(source_path)
            else:
                print(f"❌ File not found: {source_file}")
        else:
            # Process all approved content
            approved_files = self.find_approved_content()
            print(f"Found {len(approved_files)} approved files\n")

            for file in approved_files[:3]:  # Limit to 3 for demo
                self.process_content(file)

        print("\n✅ LinkedIn post generation complete")


def main():
    import sys

    vault_path = Path(__file__).parent.parent.parent
    poster = LinkedInPoster(vault_path)

    # Check if specific file provided
    if len(sys.argv) > 1:
        poster.run(sys.argv[1])
    else:
        poster.run()


if __name__ == "__main__":
    main()
